-- ITEM_INFO: ITEM_ID, ITEM_NAME, RARITY, PRICE
-- ITEM_TREE: ITEM_ID, PARENT_ITEM_ID

-- ROOT 아이템을 찾아(PARENT_ITEM_ID가 NULL) 아이템명을 출렴하라

SELECT
    i.ITEM_ID
    , i.ITEM_NAME
FROM 
    ITEM_INFO i
    JOIN ITEM_TREE t
    ON i.ITEM_ID = t.ITEM_ID
WHERE
    t.PARENT_ITEM_ID IS NULL
ORDER BY
    i.ITEM_NAME
    ;