-- ANIMAL_INS: ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE


SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (
                SELECT MIN(DATETIME) 
                FROM ANIMAL_INS)
;