-- PRODUCT: PRODUCT_ID, PRODUCT_CODE, PRICE
-- OFFLINE_SALE: OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE

-- 상품코드 별 매출액(PRICE * SALES_AMOUNT) 합계를 출력하는 쿼리를 작성
-- 매출액 기준 내림차순 정렬, 상품코드 기준으로 오름차순 정렬

SELECT p.PRODUCT_CODE, SUM(p.PRICE * o.SALES_AMOUNT) AS SALES
FROM PRODUCT AS p
JOIN OFFLINE_SALE AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC
;