-- REST_INFO: REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, PARKING_LOT, ADDRESS, TEL

-- FOOD_TYPE별로 FAVORITES 수가 가장 많은 식당의 FOOD_TYPE, REST_ID, FAVORITES_NUM을 조회, ORDER BY FOOD_TYPE DESC


SELECT FOOD_TYPE
     , REST_ID
     , REST_NAME
     , FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
                                 FROM REST_INFO
                                 GROUP BY FOOD_TYPE)
ORDER BY 1 DESC;