-- REST_INFO: REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, PARKING_LOT, ADDRESS, TEL
-- REST_REVIEW: REVIEW_ID, REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT,REVIEW_DATE

-- 서울에 위치한 식당들의 REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2)
-- ORDER BY 평균점수 기준으로 내림차순, FAVORITES DESC

SELECT i.REST_ID
    , i.REST_NAME
    , i.FOOD_TYPE
    , i.FAVORITES
    , i.ADDRESS
    , ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO i
    JOIN REST_REVIEW r
    ON i.REST_ID = r.REST_ID
WHERE (i.ADDRESS LIKE '서울특별시%') | (i.ADDRESS LIKE '서울시%')
GROUP BY i.REST_ID
ORDER BY SCORE DESC, i.FAVORITES DESC
;


/*
SELECT *
FROM REST_INFO i
    JOIN REST_REVIEW r
    ON i.REST_ID = r.REST_ID
WHERE (i.ADDRESS LIKE '서울특별시%') | (i.ADDRESS LIKE '서울시%')
    ;
    
*/