-- FISH_INFO: ID, FISH_TYPE, LENGTH, TIME
-- FISH_NAME_INFO: FISH_TYPE, FISH_NAME

-- FISH_NAME_INFO에서 물고기의 종류별 물고기의 이름과, 잡은 수를 출력

SELECT COUNT(i.ID) AS FISH_COUNT, n.FISH_NAME
FROM FISH_NAME_INFO AS n
    JOIN FISH_INFO AS i
    ON n.FISH_TYPE = i.FISH_TYPE
GROUP BY n.FISH_NAME
ORDER BY COUNT(i.ID) DESC
;
