-- PATIENT: PT_NO, PT_NAME, GEND_CD, AGE, TLNO

-- 12세 이하인 여자 환자의 PT_NAME, PT_NO, AGE, TLNO 조회
-- 전화번호가 NULL인 경우 NONE으로 출력
-- ORDER BY AGE DESC, PT_NAME

SELECT PT_NAME, PT_NO, GEND_CD, AGE, ifnull(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE (AGE <= 12) AND (GEND_CD LIKE 'W')
ORDER BY AGE DESC, PT_NAME
;