-- DOCTOR: DR_NAME, DR_ID, LCNS_NO, HIRE_YMD, MCDP_CD, TLNO
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE (MCDP_CD LIKE 'CS') | (MCDP_CD LIKE 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC
;