-- MEMBER_PROFILE: MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH
-- 생일이 3월인 여성

SELECT MEMBER_ID
        , MEMBER_NAME
        , GENDER
        , DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE (month(DATE_OF_BIRTH) LIKE '3') 
    && (GENDER LIKE 'W')
    && (TLNO IS NOT NULL)
ORDER BY MEMBER_ID
;