-- ITEM_INFO: ITEM_ID, ITEM_NAME, RARITY, PRICE
-- ITEM_TREE: ITEM_ID, PARENT_ITEM_ID

-- PARENT <-> ROOT ITEM (NULL)

-- RARITY가 'RARE'인 아이템들의 부모 아이템 정보를 출력 (ITEM_ID, ITEM_NAME, RARITY)

SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t
ON i.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO c
ON t.ITEM_ID = c.ITEM_ID
WHERE (i.RARITY = 'RARE')
ORDER BY c.ITEM_ID DESC
;