-- APPOINTMENT: APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_CNCL_YN, APNT_CNCL_YMD

-- 2022년 5월 예약한 환자(PT_NO) 수를 진료과코드(MCDP_CD) 별로 조회
SELECT 
    MCDP_CD AS '진료과 코드'
    , COUNT(PT_NO) AS '5월예약건수'
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-05%'
GROUP BY MCDP_CD
ORDER BY
    COUNT(PT_NO), MCDP_CD
;