-- BOOK: BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE


SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE (year(PUBLISHED_DATE) LIKE '2021') && (CATEGORY LIKE '인문')
ORDER BY PUBLISHED_DATE
;