-- FIRST_HALF: SHIPMENT_ID, FLAVOR, TOTAL_ORDER
-- ICECREAM_INFO: FLAVOR, INGREDIENT_TYPE

-- 각 아이스크림의 성분 타입과 성분 타입에 대한 아이스크림의 총 주문량을 조회

SELECT i.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF f
    JOIN ICECREAM_INFO i
    ON f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER) 
;