-- HR_DEPARTMENT: DEPT_ID, DEPT_NAME_KR, DEPT_NAME_EN, LOCATION
-- HR_EMPLOYEES: EMP_NO, EMP_NAME, DEPT_ID, POSITION, EMAIL, COMP_TEL, HIRE_DATE, SAL

-- 부서별 연봉의 평균을 구하기. 부서 ID, 영문 부서명, 평균 연봉을 조회
-- 평균 연봉은 ROUND(AVG(SAL), 0) AS AVG_SAL
-- ORDER BY AVG_SAL DESC

SELECT emp.DEPT_ID, dep.DEPT_NAME_EN, ROUND(AVG(emp.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS dep
JOIN HR_EMPLOYEES AS emp
ON dep.DEPT_ID = emp.DEPT_ID
GROUP BY emp.DEPT_ID
ORDER BY AVG_SAL DESC
;
