
-- CAR_RENTAL_COMPANY_CAR: CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS

-- 네비게이션 옵션이 포함된, '네비게이션' IN OPTIONS 를 만족하는 자동차의 정보를
-- ID DESC

SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC
;